name: bazaar

services:
  catalog-service:
    container_name: catalog-service
    image: rogeriofrsouza/bazaar-catalog-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: catalog-service-db
    depends_on:
      catalog-service-db:
        condition: service_healthy
