name: bazaar

services:
  config-server:
    container_name: config-server
    image: rogeriofrsouza/bazaar-config-server
    ports:
      - "8888:8888"

  discovery-server:
    container_name: discovery-server
    image: rogeriofrsouza/bazaar-discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    container_name: api-gateway
    image: rogeriofrsouza/bazaar-api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      DISCOVERY_SERVER_URL: ${DISCOVERY_SERVER_URL}
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started

  catalog-service:
    container_name: catalog-service
    image: rogeriofrsouza/bazaar-catalog-service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${CATALOG_DB_URL}
      DB_USERNAME: ${CATALOG_DB_USERNAME}
      DB_PASSWORD: ${CATALOG_DB_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      DISCOVERY_SERVER_URL: ${DISCOVERY_SERVER_URL}
    depends_on:
      catalog-service-db:
        condition: service_healthy
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started

  inventory-service:
    container_name: inventory-service
    image: rogeriofrsouza/bazaar-inventory-service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      DB_URL: ${INVENTORY_DB_URL}
      DB_USERNAME: ${INVENTORY_DB_USERNAME}
      DB_PASSWORD: ${INVENTORY_DB_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      DISCOVERY_SERVER_URL: ${DISCOVERY_SERVER_URL}
    depends_on:
      inventory-service-db:
        condition: service_healthy
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
