name: bazaar

services:
  catalog-service:
    container_name: catalog-service
    image: bazaar/catalog-service
    build:
      context: ..
      target: development
      dockerfile: catalog-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_HOST: catalog-service-db
    depends_on:
      catalog-service-db:
        condition: service_healthy
