name: bazaar

services:
  catalog-service-db:
    container_name: catalog-service-db
    image: postgres:18-alpine
    ports:
      - "${CATALOG_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${CATALOG_DB_USERNAME}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_DB: catalog
    volumes:
      - catalog-service-db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  catalog-service-db-data:
