server:
  port: 8888

spring:
  application:
    name: config-server
  threads:
    virtual:
      enabled: true
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/rogeriofrsouza/bazaar-config.git}
          default-label: ${CONFIG_GIT_LABEL:main}
          clone-on-start: true
